### ISSUE TITLE
file_get_contents(/tmp/adminer.invalid): Failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by ericc-dream** [pematon/adminer#1]
Hi 

Thanks for your work trying to make adminer working on 8.3
I was ready to doing it, when I saw your message in one of the "pull request" on the main site 
So I downloaded your version 4.9.3, and I found a little issue with the "editor" (editor-4.9.3-en.php) : 
Right after login, I see this error message 
`( ! ) Warning: file_get_contents(/tmp/adminer.invalid): Failed to open stream: No such file or directory in /home/crasteer/www/adminer/editor.php on line 1430`
with xdebug ! 
This is something I had already "corrected" on my side, in adminer-master/adminer/include/auth.inc.php , line 43:
```
	if (file_exists(get_temp_dir() . "/adminer.invalid")) {
		$invalids = unserialize(@file_get_contents(get_temp_dir() . "/adminer.invalid")); // @ - may not exist
	} else {
		$invalids = "";
	}
```
I think that the "@" is even not required/supported any more

**Comment by peterpp** [comment]
Thank you for reporting. As I know, `@` operator is still valid and functional. Is there any chance, you have `xdebug.scream` set to 1 in your php.ini file? This configuration disables effect of error suppression operator.

I can add a condition as you suggest, but `@` is used on many places in Adminer. So the chance you will run into the similar problem on another place is quite high.

**Comment by peterpp** [comment]
In general, it is good to avoid error suppressing. So I've made first two quick changes here: https://github.com/pematon/adminer/commit/a494827dc5b6fc54e2324ea4467a0d44130768e2

**Comment by ericc-dream** [comment]
yes, indeed ... This is my development machine with xdebug.scream = true 
The issue with "@" is that the script crash and you don't know why ... and sometime to reproduce or understand what the user have done is almost impossible (because they don't know themself :-) )

**Comment by peterpp** [comment]
I've rewritten all functions for opening/writing to files. This should be enough for now.

In `version-5` branch, I removed another warning suppression. If you are interested, I would be glad if you help me with testing.
