### ISSUE TITLE
editor.php , unable to load the default.css

### ISSUE THREAD

**Issue by ericc-dream** [pematon/adminer#2]
Hi 

Sorry, I have another issue with "editor.php" 
When call it, with the web developer tools in Firefox, I see that it try to download a file "editor.php?file=default.css&version=1c2a188d".
If I click on this URL, I have a "scrambled" file, unreadable ... and of course, no css in the web page 

With the "old" version, the file is "editor.php?file=default.css&version=4.8.1" , and perfectly readable ! 
Not sure what is the reason of this !

**Comment by ericc-dream** [comment]
using editor-4.9.3-mysql-en.php works as expected ! 
The default.css is loaded and readable ... (?file=default.css&version=2357e271)

**Comment by peterpp** [comment]
So is it OK? Can we close the issue?

**Comment by ericc-dream** [comment]
editor-4.9.3-mysql-en.php is OK 
but 
 editor-4.9.3-en.php  is not ... in this one, the LZW compress/decompress went wrong apparently

**Comment by peterpp** [comment]
I can't reproduce the problem on my environment. It's odd that one exported file works and another doesn't.

**Comment by ericc-dream** [comment]
I tried again and I can't reproduce neither 
Strange !  I didn't do anything special yesterday and I have done the same procedure today 
I will close the issue, then
