### ISSUE TITLE
adminer-version 5

### ISSUE THREAD

**Issue by ericc-dream** [pematon/adminer#3]
As you asked, I downloaded the branch version-5 (as zip) and decompress it on my test machine 
for context: 
Server
Ubuntu 20.04 LTS 
Apache 2.4.41 
PHP 8.3.12

Client
Firefox 131 (Linux) 

editor: 
1 table with a lot of "enum" 
Select 1 enum value, then press "Select" 
( ! ) Warning: Array to string conversion in ~/www/adminer-version-5/editor/include/adminer.inc.php on line 356

and after 
( ! ) Warning: Cannot modify header information - headers already sent by (output started at ~/www/adminer-version-5/editor/include/adminer.inc.php:356) in ~/www/adminer-version-5/adminer/include/design.inc.php on line 114
(and following lines, 115, 116, 117, 118, 119, 125)

**Comment by peterpp** [comment]
Thank! Fixed in the master branch together with another problem I found.
