### ISSUE TITLE
Fatal error in single language version

### ISSUE THREAD

**Issue by lumpysimon** [pematon/adminer#4]
Hi

Single language versions (e.g. `adminer-4.10-mysql-en.php` or `adminer-4.11-en.php`) cause a fatal error due to the missing function `switch_lang`:

`Fatal error: Uncaught Error: Call to undefined function switch_lang() in /Users/aaaaa/www/db/index.php:1412 Stack trace: #0 /Users/aaaaa/www/db/index.php(1772): page_footer() #1 /Applications/Herd.app/Contents/Resources/valet/server.php(167): require('/Users/aaaaa...') #2 {main} thrown in /Users/aaaaa/www/db/index.php on line 1412`

The multi-language versions work fine.

**Comment by peterpp** [comment]
Thank you for the report, compilation is fixed. I also uploaded new compiled files to both releases.

**Comment by lumpysimon** [comment]
Thank you, works perfectly now 👍
