### ISSUE TITLE
MSSQL connection

### ISSUE THREAD

**Issue by rktype** [pematon/adminer#5]
Due to unsecure connection between containers in a docker stack, the mssql configuration connection should have the option `"TrustServerCertificate" => true` in adminer/adminer/drivers/mssql.inc.php

**Comment by peterpp** [comment]
Ignoring self-signed server certificate means a security risk in general, so is should be an optional configuration. I added support for `Encrypt` and `TrustServerCertificate` options that to AdminerLoginSsl plugin.

Usage:
```php
<?php
function adminer_object() {
    include_once "../plugins/plugin.php";
    include_once "../plugins/login-ssl.php";

    $plugins = [
        new AdminerLoginSsl(["TrustServerCertificate" => true]),
    ];

    return new AdminerPlugin($plugins);
}

include "./adminer.php";
```
